version: '3.3'

volumes:
  
  goomba-data:
    driver: local

services:

  nats:
    container_name: goomba_nats
    hostname: nats
    restart: on-failure
    image: nats:latest
    ports:
      - "4222"
      - "8222"
      - "6222"
    logging:
      driver: json-file
      options:
        max-size: 1m

  goomba:
    container_name: goomba_goomba
    hostname: goomba
    restart: on-failure
    image: goomba/goomba:latest
    ports:
      - "8081"
      - "8082"
    volumes:
      - goomba-data:/opt/goomba-data
    logging:
      driver: json-file
      options:
        max-size: 1m
